### ISSUE TITLE
Default branch should be "main" not "master"

### ISSUE THREAD

**Issue by juancpineda97** [ad-m/github-push-action#68]
Due to the latest changes to Github, the default branches are now called "main" and not "master". Therefore, the default branch should be "main".

**Comment by ouuan** [comment]
Why not use `${{ github.ref }}` as default? (Another breaking change, though.)

**Comment by counter2015** [comment]
It's strange when I see my workflow failed due to this reason.
Since it's a break strange, why not update another version of workflow instread of modifying it directly？

**Comment by ad-m** [comment]
@counter2015 , there is no release yet and there is no updates of already released version. Use latest version. `master` detect branch automatically and should not raise issues like that.

**Comment by counter2015** [comment]
> @counter2015 , there is no release yet and there is no updates of already released version. Use latest version. `master` detect branch automatically and should not raise issues like that.

@ad-m I'm not sure, you mean  that this issue is fixed in master version?

I didn't specify version, and the `ad-m/github-push-action@master` version like following:
```
    - name: Push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
```

I fixed it by following steps
- delete `main` branch 
- use `github.ref` in config
- trigger wrokflow manually by `on: workflow_dispatch`

```
    - name: Push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: master
 ```

**Comment by ad-m** [comment]
PR #69 switch default branch to `main`. PR #75 (merged a 43 minutes ago) introduce autodiscovery of default branch (usually between `master` and `main`).

The simplest solution is use explicit branch (`branch: master`) or explicit version (`uses: ad-m/github-push-action@v0.6.0`). However, in most cases of user of `uses: ad-m/github-push-action@master` the new default configuration (branch detection) should work fine.

**Comment by nikeee** [comment]
This thing broke my build and I got a lot of mails from GitHub.

PR #75 did not fix it for me as I still got mails from GitHub. Part of the stack trace:
```
Error: Invalid status code: 404
    at IncomingMessage.<anonymous> (/home/runner/work/_actions/ad-m/github-push-action/master/start.js:14:21)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1184:12)
```
This may be caused by the repository being private.

Fixed by specifying the branch explicitly using `branch: master`.
_Lesson learned_: Don't rely on `@master` (please, don't change that name aswell). Maybe the sample in the readme should always use the latest stable tag instead of `@master`.

**Comment by ad-m** [comment]
@nikeee , are you using public GitHub instance or GitHub EE or something like that? Actions use GitHub token, so it should works for private repositories too.

I added extra logging to see what is missing 821c9b7 .

**Comment by nikeee** [comment]
The `res` object (that gets assigned to the error) contained these fields:
```
    url: '',
    method: null,
    statusCode: 404,
```
The request (`res.req`) contained these fields:
```
      _header: 'GET /repos/<my-gh-name>/<my-private-repo> HTTP/1.1\r\n' +
        'User-Agent: github.com/ad-m/github-push-action\r\n' +
        'Host: api.github.com\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      path: '/repos/<my-gh-name>/<my-private-repo>',
```

**Comment by ad-m** [comment]
I believe authorization issue is solved in commit 057a6ba835d986bfe495dd476a6c4db1d5f9503c . No longer `branch: master` is necessary and discovery of branch should works without any issues.
